// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqDlm38EdtTeIBXbP9aLmc9GQNjabViPY',
    appId: '1:459439843528:web:97d9f151cbfa5c38549dfd',
    messagingSenderId: '459439843528',
    projectId: 'huminiai',
    authDomain: 'huminiai.firebaseapp.com',
    storageBucket: 'huminiai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB45DsOVGCFmCR4USA-0d4U_-LCGK5pjQ8',
    appId: '1:459439843528:android:bf755a49d6b459ad549dfd',
    messagingSenderId: '459439843528',
    projectId: 'huminiai',
    storageBucket: 'huminiai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAwN9Bgv_uYycuH135kBCkwFVUPZrmen8',
    appId: '1:459439843528:ios:3c5f3a95c2e9eba8549dfd',
    messagingSenderId: '459439843528',
    projectId: 'huminiai',
    storageBucket: 'huminiai.firebasestorage.app',
    iosClientId: '459439843528-g9kgie0dmlcet95qev3n018sfi6uk11p.apps.googleusercontent.com',
    iosBundleId: 'com.example.huminiAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAwN9Bgv_uYycuH135kBCkwFVUPZrmen8',
    appId: '1:459439843528:ios:3c5f3a95c2e9eba8549dfd',
    messagingSenderId: '459439843528',
    projectId: 'huminiai',
    storageBucket: 'huminiai.firebasestorage.app',
    iosClientId: '459439843528-g9kgie0dmlcet95qev3n018sfi6uk11p.apps.googleusercontent.com',
    iosBundleId: 'com.example.huminiAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqDlm38EdtTeIBXbP9aLmc9GQNjabViPY',
    appId: '1:459439843528:web:97d9f151cbfa5c38549dfd',
    messagingSenderId: '459439843528',
    projectId: 'huminiai',
    authDomain: 'huminiai.firebaseapp.com',
    storageBucket: 'huminiai.firebasestorage.app',
  );

}